"""
Phase 1: Core Order Model — Signal, Order, Position, Trade dataclasses.

Architecture doc: docs/findings/order_model_architecture.md

Design decisions (confirmed):
  - Gap fills (open beyond TP/SL)   → fill at open price
  - TP vs exit_signal same bar       → TP wins
  - TP/SL modification mid-trade     → no (fixed after placement)
  - File structure                   → new files
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional, Tuple

import pandas


# ─────────────────────────────────────────────────────────────────────────────
# Enums
# ─────────────────────────────────────────────────────────────────────────────

class SignalType(Enum):
    """Generated by strategy at T close."""
    ENTRY = "entry"
    EXIT  = "exit"


class OrderType(Enum):
    """Sent to broker at T+1 morning."""
    BUY         = "buy"          # Market buy
    SELL        = "sell"         # Market sell (from exit signal)
    TAKE_PROFIT = "take_profit"  # Limit sell at TP price
    STOP_LOSS   = "stop_loss"    # Stop sell at SL price


class OrderStatus(Enum):
    PENDING    = "pending"     # Placed, not yet filled
    FILLED     = "filled"      # Executed
    CANCELLED  = "cancelled"   # Manually/exit-cancel removed
    EXPIRED    = "expired"     # End of backtest


class ExitReason(Enum):
    TAKE_PROFIT   = "take_profit"    # TP order filled
    STOP_LOSS     = "stop_loss"      # SL order filled
    SIGNAL_EXIT   = "signal_exit"    # Sell order from exit signal
    FORCED_EXIT   = "forced_exit"    # End of backtest, position closed


# ─────────────────────────────────────────────────────────────────────────────
# Signal  (strategy output, available at T+1 morning)
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class Signal:
    """
    Entry or exit signal generated from T's closed data.

    Attributes
    ----------
    date : pandas.Timestamp
        The date the signal fires (T).  Available at T+1 morning.
    symbol : str
        Stock ticker.
    signal_type : SignalType
        ENTRY or EXIT.
    tp_pct : float | None
        Take-profit percentage (e.g. 0.05 = 5%).  Set by adaptive TP/SL
        on ENTRY signals.
    sl_pct : float | None
        Stop-loss percentage (e.g. 0.03 = 3%).  Set by adaptive TP/SL
        on ENTRY signals.
    exit_alpha : float | None
        Exit-alpha factor for sell-side strategies (optional).
    raw_score : float | None
        Strategy raw score (optional).
    """
    date:        pandas.Timestamp
    symbol:      str
    signal_type: SignalType
    tp_pct:      Optional[float] = None
    sl_pct:      Optional[float] = None
    exit_alpha:  Optional[float] = None
    raw_score:   Optional[float] = None

    def __post_init__(self) -> None:
        if self.signal_type == SignalType.EXIT:
            # Exit signals don't carry TP/SL
            self.tp_pct = None
            self.sl_pct = None


# ─────────────────────────────────────────────────────────────────────────────
# Order  (broker instruction, placed at T+1 morning)
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class Order:
    """
    A broker order placed at T+1 open.

    Order lifecycle
    ---------------
    BUY / SELL  → FILLED immediately (same bar, at open).
    TP / SL     → PENDING initially; FILLED when trigger condition met.

    Gap-fill rule (confirmed): if the bar opens beyond the trigger price,
    fill at the bar open price instead of the trigger price.
    """
    order_id:        str = field(default_factory=lambda: uuid.uuid4().hex[:12])
    order_type:      OrderType                   = OrderType.BUY
    symbol:          str                          = ""
    date_placed:     pandas.Timestamp             = None  # type: ignore[assignment]
    expected_fill:    pandas.Timestamp             = None  # type: ignore[assignment]
    quantity:        int                          = 0
    # TP / SL
    trigger_price:   Optional[float]             = None  # Activate when price >= this
    limit_price:     Optional[float]             = None  # Fill price cap (TP)
    sl_activation:   Optional[pandas.Timestamp]  = None  # SL only active after this date
    # Execution
    fill_date:       Optional[pandas.Timestamp]  = None
    fill_price:      Optional[float]             = None
    status:          OrderStatus                  = OrderStatus.PENDING
    # Linkage
    parent_order_id: Optional[str]               = None  # TP/SL → parent BUY order_id
    cancel_reason:   Optional[str]               = None  # Why CANCELLED

    # ── derived helpers ──────────────────────────────────────────────────────

    def is_active(self) -> bool:
        return self.status == OrderStatus.PENDING

    def is_filled(self) -> bool:
        return self.status == OrderStatus.FILLED

    def is_tp_or_sl(self) -> bool:
        return self.order_type in (OrderType.TAKE_PROFIT, OrderType.STOP_LOSS)

    def is_buy(self) -> bool:
        return self.order_type == OrderType.BUY

    def is_sell(self) -> bool:
        return self.order_type == OrderType.SELL


# ─────────────────────────────────────────────────────────────────────────────
# Position  (active state after BUY fills)
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class Position:
    """
    An active long position held between BUY fill and final SELL fill.

    Attributes
    ----------
    symbol : str
    entry_date : pandas.Timestamp
        T+1 (the bar the BUY order filled).
    entry_price : float
        T+1 open price.
    quantity : int
        Shares bought.
    tp_trigger : float | None
        TP trigger price = entry_price × (1 + tp_pct).
    sl_trigger : float | None
        SL trigger price = entry_price × (1 - sl_pct).
    sl_active_date : pandas.Timestamp
        Date from which SL is checked (entry_date + min_hold bars).
    open_order_ids : List[str]
        Order IDs still pending for this position (TP, SL, SELL).
    highest_high_since_entry : float
        Track for future trailing-SL enhancements.
    unrealized_pnl : float
        Current unrealized P&L (updated each bar).
    """
    symbol:                     str                          = ""
    entry_date:                 pandas.Timestamp             = None  # type: ignore[assignment]
    entry_price:                float                        = 0.0
    quantity:                   int                          = 0
    tp_trigger:                 Optional[float]             = None
    sl_trigger:                 Optional[float]             = None
    sl_active_date:             Optional[pandas.Timestamp]  = None
    open_order_ids:             List[str]                    = field(default_factory=list)
    highest_high_since_entry:   float                        = 0.0
    unrealized_pnl:             float                        = 0.0
    # Bar-level excursion tracking
    bar_excursions:             Optional[List[Tuple[
        pandas.Timestamp, float, float
    ]]]                         = None  # (date, high_pct, low_pct)
    max_favorable_pct:          Optional[float]               = None
    max_adverse_pct:            Optional[float]               = None
    mfe_date:                   Optional[pandas.Timestamp]     = None
    mae_date:                   Optional[pandas.Timestamp]     = None
    # Meta
    set_label:                  Optional[str]                = None  # Strategy set label
    tp_pct:                     Optional[float]               = None  # TP% used at entry
    sl_pct:                     Optional[float]               = None  # SL% used at entry

    def update_unrealized(self, current_price: float) -> None:
        self.unrealized_pnl = (current_price - self.entry_price) * self.quantity

    def update_high(self, high_price: float) -> None:
        if high_price > self.highest_high_since_entry:
            self.highest_high_since_entry = high_price

    def net_value(self, price: float) -> float:
        return self.entry_price * self.quantity + self.unrealized_pnl


# ─────────────────────────────────────────────────────────────────────────────
# Trade  (completed position, output of backtest)
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class Trade:
    """
    A completed round-trip trade.

    Notes on exit_reason
    --------------------
    - TAKE_PROFIT : TP order filled (either intrabar high >= trigger, or gap-open
                    at bar open >= trigger — in both cases fill_price = min(fill,
                    trigger) per intrabar price priority).
    - STOP_LOSS   : SL order filled (same logic, low side).
    - SIGNAL_EXIT : SELL market order filled at T+1 open after exit signal.
    - FORCED_EXIT : Backtest ended while position still open; closed at last bar
                    close.
    """
    symbol:              str                           = ""
    entry_date:         pandas.Timestamp               = None  # type: ignore[assignment]
    entry_price:        float                         = 0.0
    exit_date:          Optional[pandas.Timestamp]    = None
    exit_price:         Optional[float]               = None
    quantity:           int                           = 0
    pnl:                float                         = 0.0
    holding_period:     int                           = 0          # calendar days
    exit_reason:        ExitReason                    = ExitReason.FORCED_EXIT

    # ── execution quality ───────────────────────────────────────────────────
    tp_triggered:       bool                          = False
    sl_triggered:       bool                          = False
    signal_exit_fired:  bool                          = False

    # ── TP/SL levels used ──────────────────────────────────────────────────
    tp_trigger_price:   Optional[float]               = None  # For reference
    sl_trigger_price:   Optional[float]               = None

    # ── bar-level excursion tracking ────────────────────────────────────────
    max_favorable_pct:  Optional[float]               = None
    max_adverse_pct:    Optional[float]               = None
    mfe_date:           Optional[pandas.Timestamp]     = None
    mae_date:           Optional[pandas.Timestamp]     = None
    bar_excursions:     Optional[List[Tuple[
        pandas.Timestamp, float, float
    ]]]                 = None  # (date, high_pct, low_pct) relative to entry_price

    # ── meta ────────────────────────────────────────────────────────────────
    order_id:           Optional[str]                  = None  # Parent BUY order
    set_label:          Optional[str]                  = None  # Strategy set (A/B/C)

    @property
    def pct_return(self) -> float:
        if self.entry_price <= 0:
            return 0.0
        return self.pnl / (self.entry_price * self.quantity)

    def to_dict(self) -> Dict:
        return {
            "symbol":            self.symbol,
            "entry_date":        str(self.entry_date.date()) if self.entry_date else "",
            "entry_price":       self.entry_price,
            "exit_date":         str(self.exit_date.date()) if self.exit_date else "",
            "exit_price":        self.exit_price,
            "quantity":          self.quantity,
            "pnl":               self.pnl,
            "holding_period":    self.holding_period,
            "exit_reason":       self.exit_reason.value,
            "tp_triggered":      self.tp_triggered,
            "sl_triggered":      self.sl_triggered,
            "signal_exit_fired": self.signal_exit_fired,
            "tp_trigger_price":  self.tp_trigger_price,
            "sl_trigger_price": self.sl_trigger_price,
            "pct_return":        self.pct_return,
            "set_label":         self.set_label,
        }
